let revenueData = [ { name: "Medical Center", value: 45, color: "#F0BF00"}, 
{ name: "Student Fees", value: 4, color: "#F6E50E"}, 
{ name: "State of California", value: 8, color: "#FFF688" }, 
{ name: "Tuition", value: 11, color: "#5F63EC" }, 
{ name: "Research Grants and Contracts", value: 13, color: "#71A8FF"}, 
{ name: "Pell Grants", value: 1, color: "#58C9FB" }, 
{ name: "Non-educational Services", value: 11, color: "#0F7AB4"}, 
{ name: "Gifts, Endowments, Interest, Etc.", value: 7, color: "#D4E4FF" } ]

let blankRevenueData = [ { name: "Medical Center", value: 0, color: "#F0BF00"}, 
{ name: "Student Fees", value: 0, color: "#F6E50E"}, 
{ name: "State of California", value: 0, color: "#FFF688" }, 
{ name: "Tuition", value: 0, color: "#5F63EC" }, 
{ name: "Research Grants and Contracts", value: 0, color: "#71A8FF"}, 
{ name: "Pell Grants", value: 0, color: "#58C9FB" }, 
{ name: "Non-educational Services", value: 0, color: "#0F7AB4"}, 
{ name: "Gifts, Endowments, Interest, Etc.", value: 0, color: "#D4E4FF" } ]



let revenueDescriptions = [
  "A large, not-for-profit regional medical center, including multiple hospitals, labs and clinics. Income comes from patients, medical insurance companies, and government programs like medicare.",
  "Fees are dedicated to specific services, such as athletic facilities, bus service (UNITRANS), student organizations, the CoHo and Student Community Center, etc.",
  "General funds given by the taxpayers of California, appropriated annualy by the state legislature. General funds are not dedicated to specific services.",
  "Students pay tuition to attend the University. Non-California residents pay about twice as much as residents.  Tuition is also general funds.",
  "Government and industry funds given to faculty and graduate students to perform research projects. These include up to 50% overhead in addition to the cost of the research.",
  "Federal grants for tuition and living expenses for low-income students. Percentage of students with Pell grants is a good way to measure who a University serves; at UCD, it's 34%; at Cal Tech it's 14%; at Sac State it's 71%.",
  "Services other than education that people pay for, like dorms, dining, parking, etc.  At UC Davis, this also includes almost $500M of revenue generated by medical school faculty, or 8%, making this category look really big.",
  "Endowments are past gifts that were invested to provide income; interest is earned on other savings. The Museum is the direct result of a $10M gift from Jan Shrem and Maria Manetti Shrem."

]



let expenditureData = [ { name: "Medical Center", value: 43, color: "#F0BF00"}, 
{ name: "Teaching and Teaching Support", value: 23, color: "#F6E50E" }, 
{ name: "Research", value: 11, color: "#FFF688"  }, 
{ name: "Student Services and Financial Aid", value: 8, color: "#5F63EC" }, 
{ name: "Operations and Maintenance", value: 2, color: "#71A8FF" }, 
{ name: "Administration", value: 3, color: "#58C9FB"  }, 
{ name: "Non-Educational Services", value: 2, color: "#0F7AB4" }, 
{ name: "Public Service", value: 2, color: "#D4E4FF" }, 
{ name: "Depreciation, Interest, etc.", value: 6, color:"#FFFFFF"} ]

let blankExpenditureData = [ { name: "Medical Center", value: 0, color: "#F0BF00"}, 
{ name: "Teaching and Teaching Support", value: 0, color: "#F6E50E" }, 
{ name: "Research", value: 0, color: "#FFF688"  }, 
{ name: "Student Services and Financial Aid", value: 0, color: "#5F63EC" }, 
{ name: "Operations and Maintenance", value: 0, color: "#71A8FF" }, 
{ name: "Administration", value: 0, color: "#58C9FB"  }, 
{ name: "Non-Educational Services", value: 0, color: "#0F7AB4" }, 
{ name: "Public Service", value: 0, color: "#D4E4FF" }, 
{ name: "Depreciation, Interest, etc.", value: 0, color:"#FFFFFF"} ]

let expenditureDescriptions = [
  "The cost of providing care at the Medical Center is roughly what we get paid to provide it.",
  "Professors, advisors, deans, the library, the computer labs, etc, including Medical School faculty salaries.",
  "The costs of doing the research, mostly researcher salaries.",
  "Student Health, things covered by fees, Admissions, and also financial aid from the general funds, which is about $100M or 1.5%.",
  "Upkeep of the grounds and building, and utilities, which are less than 1%.",
  "Provost and Chancellor's offices, raising money, accounting, personnel, legal, making budgets.",
  "The costs of providing dorms, dining, parking, etc.",
  "Mostly the cooperative extension, which provides agricultural services to farmers, ranchers, winemakers, etc.  Part of our mission as a land grant university.",
  "Depreciation is the loss of value of buildings and equipment as they wear out. Mostly unavoidable financial losses."


]




// For extra colors, use: https://piazza.com/class/kmtj79sflgi5m?cid=967


let Data = {
  revenueData: revenueData,
  blankRevenueData: blankRevenueData,
  revenueDescriptions: revenueDescriptions,

  expenditureData: expenditureData,
  blankExpenditureData: blankExpenditureData,
  expenditureDescriptions: expenditureDescriptions,
}

export default Data;
